# Generated by Django 3.0.8 on 2020-07-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0002_auto_20200724_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='detection',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
