# Generated by Django 3.0.8 on 2020-08-08 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0003_auto_20200725_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camid', models.SmallIntegerField(null=True)),
                ('location', models.CharField(default='', max_length=70)),
                ('camModel', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Detections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suspect', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('familyName', models.CharField(max_length=30)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'UNKNOWN')], default='U', max_length=2)),
                ('face_Descriptor', models.TextField(default='')),
                ('Danger_degree', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('contientAlert', models.BooleanField(default=0)),
                ('camera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='detections.Camera', verbose_name='Person')),
                ('persons', models.ManyToManyField(through='detections.Detections', to='detections.Person', verbose_name='Detections')),
            ],
        ),
        migrations.DeleteModel(
            name='Detection',
        ),
        migrations.AddField(
            model_name='detections',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detections.Person', verbose_name='Person'),
        ),
        migrations.AddField(
            model_name='detections',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='detections.Video', verbose_name='Video'),
        ),
    ]
