# Generated by Django 3.0.8 on 2020-08-08 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0004_auto_20200808_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='Danger_degree',
        ),
        migrations.RemoveField(
            model_name='person',
            name='face_Descriptor',
        ),
    ]
