# Generated by Django 3.0.8 on 2020-08-08 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0005_auto_20200808_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='camera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='detections.Camera', verbose_name='Camera'),
        ),
    ]
