# Generated by Django 3.0.8 on 2020-08-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0006_auto_20200808_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='familyName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='firstName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
