# Generated by Django 3.0.8 on 2020-08-13 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0009_auto_20200813_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suspect', models.BooleanField(default=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detections.Person', verbose_name='Person')),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='detections.Video', verbose_name='Video')),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='persons',
            field=models.ManyToManyField(through='detections.Detections', to='detections.Person', verbose_name='Detections'),
        ),
    ]
