# Generated by Django 3.0.8 on 2020-08-13 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0010_auto_20200813_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='contientAlert',
        ),
    ]
