# Generated by Django 3.0.8 on 2020-08-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0013_auto_20200816_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
