# Generated by Django 3.0.8 on 2020-08-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0015_auto_20200816_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='picture',
            field=models.ImageField(default='./profile_pics/default.jpg', upload_to='profile_pics', verbose_name='default.jpg'),
            preserve_default=False,
        ),
    ]
