# Generated by Django 3.0.8 on 2020-09-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0016_person_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='remark',
            field=models.TextField(default='no remark'),
        ),
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
