# Generated by Django 3.0.8 on 2020-09-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0017_auto_20200901_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(default='empty.mp4', upload_to='videos'),
        ),
    ]
