# Generated by Django 3.0.8 on 2020-09-04 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0018_video_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video',
            new_name='videoPath',
        ),
    ]
