# Generated by Django 3.0.8 on 2020-09-05 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0020_auto_20200904_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['date', 'time', 'camera']},
        ),
    ]
