# Generated by Django 3.0.8 on 2020-10-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0022_auto_20200905_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='description_vector',
            field=models.TextField(blank=True),
        ),
    ]
